# Generated by Django 6.0 on 2025-12-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_server_joindate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='display',
        ),
    ]
