# Generated by Django 6.0 on 2026-01-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_server_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='balance',
            field=models.FloatField(default=1020, max_length=10),
        ),
    ]
