# Generated by Django 6.0 on 2025-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_delete_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
