# Generated by Django 6.0 on 2026-01-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_server_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='balance',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
